apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: project2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic3tier-api
  template:
    metadata:
      labels:
        app: basic3tier-api
    spec:
      containers:
      - name: api-container
        image: cocomo1/basic3tier-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Basic3Tier
          value: "Host=postgres-service;Port=5432;Database=basic3tier;Username=postgres;Password=admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: project2
spec:
  selector:
    app: basic3tier-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
